language: dart

dist: xenial

addons:
  apt:
    packages:
      - lib32stdc++6

install:
  - |
    if [ ! -d flutter ] ; then
      git clone https://github.com/flutter/flutter.git
    fi
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov

script:
  - cd dart/mobile
  - ../../flutter/bin/flutter test --coverage

after_success:
  - coveralls-lcov coverage/lcov.info

cache:
  directories:
    - flutter
    - $HOME/.pub-cache
