targets:
  $default:
    sources:
      - "src/**"
      - "lib/**"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
          - src/**
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - --minify
